app:
  name: "test"
  runMode: debug #release
  version: 2001
  configPath: config/
  msgPath: msg/sproto/all.json
  logPath: logs/
  logFile: apps
  timeFormat:  20060102
  netType: "ws" 
  serverType: "gate"
  serverName: "gate1"
  ip: 0.0.0.0
  ipOut: 192.168.0.105
  port: 8001
  conTypes:
    - "app"
    - "gate"
    - "login"
  etcd:
    Hosts:
      - "http://192.168.0.105:2379"
    Url: "http://192.168.0.105:2379"

  nats:
    Hosts:
      - "nats:rg1q2w3e@192.168.0.105:4242"
    Url: ""







